// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLHUipFa-Sa-bfGcdfVCc_kfanh1usBh8',
    appId: '1:1047166827214:web:0b846d7aaa283db2b66e9f',
    messagingSenderId: '1047166827214',
    projectId: 'digitalvisitorlog-bd3a4',
    authDomain: 'digitalvisitorlog-bd3a4.firebaseapp.com',
    storageBucket: 'digitalvisitorlog-bd3a4.firebasestorage.app',
    measurementId: 'G-7MQVW1L3R1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGuVuNds3UodxNLYrZQ1qvyhBqqaWBZe8',
    appId: '1:1047166827214:android:7ba6c0fc01c95c11b66e9f',
    messagingSenderId: '1047166827214',
    projectId: 'digitalvisitorlog-bd3a4',
    storageBucket: 'digitalvisitorlog-bd3a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkwJDghWS4Ybgchl6cvV07MDzU83ypaOk',
    appId: '1:1047166827214:ios:bb742e3992ef0168b66e9f',
    messagingSenderId: '1047166827214',
    projectId: 'digitalvisitorlog-bd3a4',
    storageBucket: 'digitalvisitorlog-bd3a4.firebasestorage.app',
    iosBundleId: 'com.example.visitorLogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkwJDghWS4Ybgchl6cvV07MDzU83ypaOk',
    appId: '1:1047166827214:ios:bb742e3992ef0168b66e9f',
    messagingSenderId: '1047166827214',
    projectId: 'digitalvisitorlog-bd3a4',
    storageBucket: 'digitalvisitorlog-bd3a4.firebasestorage.app',
    iosBundleId: 'com.example.visitorLogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLHUipFa-Sa-bfGcdfVCc_kfanh1usBh8',
    appId: '1:1047166827214:web:bb3bcbba2a2cb6fab66e9f',
    messagingSenderId: '1047166827214',
    projectId: 'digitalvisitorlog-bd3a4',
    authDomain: 'digitalvisitorlog-bd3a4.firebaseapp.com',
    storageBucket: 'digitalvisitorlog-bd3a4.firebasestorage.app',
    measurementId: 'G-M60JZ55LT2',
  );

}